# Generated by Django 3.1.5 on 2021-01-23 20:32

import binarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculaBinarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacao', models.CharField(choices=[('+', 'Soma'), ('-', 'Subtracão'), ('*', 'Multiplicação'), ('/', 'Divisão'), ('%', 'Resto da divisão')], max_length=1)),
                ('numero1', models.CharField(max_length=8, validators=[binarios.models.CalculaBinarios.validate_binarios])),
                ('numero2', models.CharField(max_length=8, validators=[binarios.models.CalculaBinarios.validate_binarios])),
            ],
        ),
    ]
